/* Prix des carburants en temps réel — code commun à l'accueil (index.html) et aux articles
 * (blog.html, repère [prix-carburants] dans le texte). Sorti tel quel de index.html le 2026-09-19.
 * Remplit #carburants-content (et #carburants-penurie) avec les données officielles
 * prix-carburants.gouv.fr (API data.economie.gouv.fr). */
function loadCarburants(){
    var API = 'https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/prix-des-carburants-en-france-flux-instantane-v2/records';
    fetch(API + '?where=within_distance(geom,geom\'POINT(5.766 45.084)\',5km)&limit=30&order_by=distance(geom,geom\'POINT(5.766 45.084)\')').then(function(r){ return r.json(); }).then(function(data){
        var records = data.results || []; if(!records.length){ document.getElementById('carburants-content').innerHTML = '<p style="color:#6E5B49;">Aucune donnee.</p>'; return; }
        var viz = records.filter(function(f){ return f.cp === '38220' && (f.id === 38220001 || f.id === 38220002 || f.id === 38220003); }), alt = records.filter(function(f){ return f.cp !== '38220'; }), html = '';
        if(viz.length){ html += '<h3 style="color:#C2632F;font-family:Spectral,serif;font-size:0.95rem;margin:0 0 0.6rem;text-align:center;">A Vizille</h3><div class="stations-grid">'; viz.forEach(function(f){ html += renderStation(f,true); }); html += '</div>'; }
        if(alt.length){ var d = alt.filter(function(f){ return f.carburants_disponibles && f.carburants_disponibles.length > 0; }); if(d.length){ html += '<h3 style="color:#A07A4E;font-family:Spectral,serif;font-size:0.85rem;margin:1rem 0 0.6rem;text-align:center;">A proximite</h3><div class="stations-grid">'; d.slice(0,6).forEach(function(f){ html += renderStation(f,false); }); html += '</div>'; } }
        document.getElementById('carburants-content').innerHTML = html;
    }).catch(function(){ document.getElementById('carburants-content').innerHTML = '<p style="color:#6E5B49;">Indisponible. <a href="https://www.prix-carburants.gouv.fr/" target="_blank" style="color:#C2632F;">prix-carburants.gouv.fr</a></p>'; });
    fetch(API+'?limit=0').then(function(r){return r.json();}).then(function(td){ var tot=td.total_count||0; if(!tot) return; return fetch(API+'?where=gazole_rupture_type%3D%22temporaire%22&limit=0').then(function(r){return r.json();}).then(function(gd){ var gR=gd.total_count||0; return fetch(API+'?where=carburants_disponibles%20is%20null&limit=0').then(function(r){return r.json();}).then(function(sd){ var s=sd.total_count||0,pS=((s/tot)*100).toFixed(1),pG=((gR/tot)*100).toFixed(1),el=document.getElementById('carburants-penurie'),c=pS>15?'#ef4444':pS>5?'#f59e0b':'#4ade80',n=pS>15?'Tendue':pS>5?'Tensions':'Normal'; el.innerHTML='<div class="carburants-penurie-title">'+n+'</div><div class="carburants-penurie-details"><strong>'+pS+'%</strong> en rupture'+(gR>0?' &middot; <strong>'+pG+'%</strong> sans Gazole':'')+'</div><div class="carburants-penurie-bar"><div class="carburants-penurie-fill" style="width:'+Math.min(pS*2,100)+'%;background:'+c+';"></div></div>'; el.classList.add('visible'); }); }); }).catch(function(){});
}
var NOMS={38220001:'Carrefour Market — RN91',38220002:'TotalEnergies — Muzet',38220003:'Intermarche Vizille',38130004:'E.Leclerc Comboire',38130005:'E.Leclerc Echirolles'};
function renderStation(f,isV){ var v=f.ville||'',vc=v.charAt(0).toUpperCase()+v.slice(1).toLowerCase(),nm=NOMS[f.id]||vc; if(!NOMS[f.id]){var sv=(f.services_service||[]).join(' ').toLowerCase(),ad=(f.adresse||'').toLowerCase();if(ad.indexOf('leclerc')>-1||sv.indexOf('leclerc')>-1) nm='E.Leclerc '+vc;} var h24=f.horaires_automate_24_24==='Oui',s='<div class="station-card"'+(isV?'':' style="opacity:0.8;"')+'>'; s+='<div class="station-name">'+nm+'</div><div class="station-addr">'+(f.adresse||'')+(isV?'':', '+vc)+'</div><div class="station-horaires">'+(h24?'24h/24':'Horaires en station')+'</div><div class="prix-grid">'; ['gazole','sp95','sp98','e10','e85','gplc'].forEach(function(c){var p=f[c+'_prix'],m=f[c+'_maj'],rt=f[c+'_rupture_type'],lb={gazole:'Gazole',sp95:'SP95',sp98:'SP98',e10:'E10',e85:'E85',gplc:'GPLc'}; if(p){var d=m?new Date(m).toLocaleDateString('fr-FR',{day:'numeric',month:'short'}):'';s+='<div class="prix-item"><div class="prix-label">'+lb[c]+'</div><div class="prix-val">'+parseFloat(p).toFixed(3)+'&euro;</div>'+(d?'<div class="prix-date">'+d+'</div>':'')+'</div>';}else if(rt==='temporaire'){s+='<div class="prix-item rupture"><div class="prix-label">'+lb[c]+'</div><div class="prix-val indispo">Rupture</div></div>';}}); s+='</div>'; var lat=f.geom?f.geom.lat:null,lon=f.geom?f.geom.lon:null; if(lat&&lon) s+='<a href="https://www.google.com/maps/search/station+essence/@'+lat+','+lon+',16z/data=!5m1!1e1" target="_blank" rel="noopener" class="station-link">Maps &rarr;</a>'; s+='</div>'; return s; }
